services:
  - type: web
    name: neofinance-backend
    env: go
    buildCommand: |
      go mod download
      go build -mod=vendor -o neofinance
    startCommand: ./neofinance
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-uri
      - key: PORT
        value: 8080